services:
  - type: web
    name: catallyst
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      mkdir -p .streamlit
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: STREAMLIT_SERVER_PORT
        value: 8080
      - key: STREAMLIT_SERVER_HEADLESS
        value: true 