[server]
enableCORS = false
enableXsrfProtection = false
port = 8080
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 